### ISSUE TITLE
Investigate build errors of project `gipsl.all.build.complex`

### ISSUE THREAD

**Issue by maxkratz** [Echtzeitsysteme/gips-tests#15]
Runtime console:
`10:24:45 ERROR [build.GipsProjectBuilder::49] - java.lang.IllegalArgumentException: Some constrains contain invalid values within arithmetic expressions, e.g., boolean values instead of arithmetic values.
`

Dev console:
```
java.lang.IllegalArgumentException: Some constrains contain invalid values within arithmetic expressions, e.g., boolean values instead of arithmetic values.
	at org.emoflon.gips.build.transformation.transformer.AttributeInConstraintTransformer.transform(AttributeInConstraintTransformer.java:43)
	at org.emoflon.gips.build.transformation.transformer.AttributeExpressionTransformer.transform(AttributeExpressionTransformer.java:62)
	at org.emoflon.gips.build.transformation.transformer.BooleanInConstraintTransformer.transform(BooleanInConstraintTransformer.java:44)
	at org.emoflon.gips.build.transformation.GipsToIntermediate.transformConstraint(GipsToIntermediate.java:411)
	at org.emoflon.gips.build.transformation.GipsToIntermediate.transformConstraints(GipsToIntermediate.java:349)
	at org.emoflon.gips.build.transformation.GipsToIntermediate.transform(GipsToIntermediate.java:86)
	at org.emoflon.gips.build.GipsProjectBuilder.build(GipsProjectBuilder.java:46)
```

**Comment by maxkratz** [comment]
With https://github.com/Echtzeitsysteme/gips-tests/pull/63, the respective project compiles again. All other (broken) parts are commented out with a TODO.
