### ISSUE TITLE
`GipsGtTerminationTest` fails when running as the whole test suite

### ISSUE THREAD

**Issue by maxkratz** [Echtzeitsysteme/gips-tests#64]
[GipsGtTerminationTest](https://github.com/Echtzeitsysteme/gips-tests/blob/main/test.suite.gips/src/test/suite/gips/gttermination/GipsGtTerminationTest.java) runs successfully when run as a single test.

When running this test as part of the whole GIPS test suite, it fails with an exception:
```
java.util.concurrent.TimeoutException: testGtTermination() timed out after 1 second
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by maxkratz** [comment]
Update: this test also fails from time to time if run standalone. In this case, one of the assertions fails.
